export const DEFAULT_QUESTIONS = [
  { key: 'q2', label: "Your name", type: 'text', scored: false, isName: true },
  { key: 'q3', label: "Will there be a neon sign?", type: 'yesno', scored: true },
  { key: 'q4', label: "Will there be a photo booth?", type: 'yesno', scored: true },
  { key: 'q5', label: "Will there be a sweetheart table?", type: 'yesno', scored: true },
  { key: 'q6', label: "Will there be a choreographed first dance?", type: 'yesno', scored: true },
  { key: 'q7', label: "Will the best man speech be over/under 5.5 minutes?", type: 'overunder', scored: true },
  { key: 'q8', label: "Will the maid of honor speech be over/under 5.5 minutes?", type: 'overunder', scored: true },
  { key: 'q9', label: "Will the best man tell the bride she looks beautiful AND thank both parents tonight?", type: 'yesno', scored: true },
  { key: 'q10', label: "Will the bride or groom's job be mentioned in maid of honor/best man speech?", type: 'yesno', scored: true },
  { key: 'q11', label: "Will there be a bouquet toss?", type: 'yesno', scored: true },
  { key: 'q12', label: "What will the cake flavor be?", type: 'choice', options: ['Vanilla', 'Chocolate', 'Fruit', 'Other'], scored: true },
  { key: 'q13', label: "Will Mr. Brightside be played?", type: 'yesno', scored: true },
  { key: 'q14', label: "Will the bride do a dress change before the after party?", type: 'yesno', scored: true },
  { key: 'q15', label: "Tie breaker — what time will the bride leave the after party?", type: 'time', scored: false, isTiebreaker: true },
];
